# Generated by Django 4.2.7 on 2024-01-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='videos',
            field=models.ManyToManyField(blank=True, to='main.video'),
        ),
    ]
